2021-09-03 08:29:35,126:INFO:IndexPage : Url hit...
2021-09-03 08:57:03,384:INFO:IndexPage:Url hit...
2021-09-03 09:03:30,804:INFO:IndexPage:Url hit...
2021-09-04 06:25:43,404:INFO:IndexPage:Url hit...
2021-09-04 06:27:02,119:INFO:IndexPage:Url hit...
2021-09-04 06:51:03,555:INFO:IndexPage:Url hit...
2021-09-04 06:55:08,743:INFO:IndexPage:Url hit...
2021-09-04 07:36:35,451:INFO:IndexPage:Url hit...
2021-09-04 07:39:56,409:INFO:IndexPage:Url hit...
2021-09-04 07:42:48,404:INFO:IndexPage:Url hit...
2021-09-04 07:45:26,860:INFO:IndexPage:Url hit...
2021-09-04 07:46:35,182:INFO:IndexPage:Url hit...
2021-09-04 07:47:21,740:INFO:IndexPage:Url hit...
2021-09-04 07:48:03,541:INFO:IndexPage:Url hit...
2021-09-04 07:50:13,444:INFO:IndexPage:Url hit...
2021-09-04 07:52:22,784:INFO:IndexPage:Url hit...
2021-09-04 07:58:09,634:INFO:IndexPage:Url hit...
2021-09-04 07:59:24,114:INFO:IndexPage:Url hit...
2021-09-04 10:04:10,432:INFO:IndexPage:Url hit...
2021-09-04 12:09:42,375:INFO:IndexPage:Url hit...
2021-09-04 12:14:54,037:INFO:IndexPage:Url hit...
2021-09-04 12:23:58,080:INFO:IndexPage:Url hit...
2021-09-04 12:30:03,967:INFO:IndexPage:Url hit...
2021-09-04 12:30:56,831:INFO:IndexPage:Url hit...
2021-09-04 12:33:29,802:INFO:IndexPage:Url hit...
2021-09-04 12:33:32,370:ERROR:IndexPage:exception occur while running function  prediction()
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I 2020 Predictive Maintenance/main.py", line 36, in prediction
    string = request.form['content'].replace(" ", "")
  File "/Users/Apple/PycharmProjects/AI4I 2020 Predictive Maintenance/venv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 377, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
2021-09-04 12:34:21,555:INFO:IndexPage:Url hit...
2021-09-04 12:37:21,367:INFO:IndexPage:Url hit...
2021-09-04 12:39:38,671:INFO:IndexPage:Url hit...
2021-09-04 12:57:59,752:INFO:IndexPage:Url hit...
2021-09-04 12:59:03,900:ERROR:IndexPage:exception occur while running function  prediction()
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I 2020 Predictive Maintenance/main.py", line 57, in prediction
    mai.predict_air_temp(data)
  File "/Users/Apple/PycharmProjects/AI4I 2020 Predictive Maintenance/MaintenancePrediction.py", line 34, in predict_air_temp
    model = pickle.load(open('static/ai4i_model.sav', 'r'))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
2021-09-04 13:00:46,266:INFO:IndexPage:Url hit...
2021-09-04 13:10:39,635:INFO:IndexPage:Url hit...
2021-09-04 13:16:59,943:INFO:IndexPage:Url hit...
2021-09-04 13:18:27,138:INFO:IndexPage:Url hit...
2021-09-04 13:19:30,233:INFO:IndexPage:Url hit...
2021-09-04 13:45:16,652:INFO:IndexPage:Url hit...
2021-09-04 14:06:19,231:INFO:IndexPage:Url hit...
2021-09-04 14:12:22,295:INFO:IndexPage:Url hit...
2021-09-04 14:19:59,914:INFO:IndexPage:Url hit...
2021-09-04 14:20:13,649:INFO:MaintenancePrediction:         Process temperature [K]  ...                          RNF
0  Prdicted value is pred on 308  ...  Prdicted value is pred on 0

[1 rows x 9 columns]
2021-09-04 14:20:22,718:INFO:MaintenancePrediction:         Process temperature [K]  ...                          RNF
0  Prdicted value is pred on 308  ...  Prdicted value is pred on 0

[1 rows x 9 columns]
2021-09-04 14:22:53,060:INFO:IndexPage:Did Profiling
2021-09-04 15:15:48,394:INFO:IndexPage:Url hit...
2021-09-04 15:43:41,341:INFO:IndexPage:Url hit...
2021-09-04 15:43:43,052:INFO:IndexPage:Did Profiling
2021-09-04 15:44:02,745:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:45:47,402:INFO:IndexPage:Url hit...
2021-09-04 15:46:06,587:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:47:38,828:INFO:IndexPage:Url hit...
2021-09-04 15:47:52,438:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:48:36,342:INFO:IndexPage:Url hit...
2021-09-04 15:48:54,041:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:50:22,216:INFO:IndexPage:Url hit...
2021-09-04 15:50:41,712:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:55:58,999:INFO:IndexPage:Url hit...
2021-09-04 15:56:13,614:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:56:57,733:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:57:39,541:INFO:IndexPage:Url hit...
2021-09-04 15:58:02,663:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:58:47,966:INFO:IndexPage:Url hit...
2021-09-04 15:59:00,848:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 15:59:59,379:INFO:IndexPage:Url hit...
2021-09-04 16:00:18,407:ERROR:MaintenancePrediction:ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
Traceback (most recent call last):
  File "/Users/Apple/PycharmProjects/AI4I2020PredictiveMaintenance/MaintenancePrediction.py", line 47, in predict_air_temp
    log.add_info_log("Prdicted value is "+pred +"pred  ")
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U18'), dtype('float64')) -> None
2021-09-04 16:01:48,327:INFO:IndexPage:Url hit...
2021-09-04 16:02:01,982:INFO:MaintenancePrediction:Prdicted value is [288.19036169]
2021-09-04 22:31:42,930:INFO:IndexPage:Url hit...
2021-09-04 22:31:49,899:INFO:IndexPage:Did Profiling
2021-09-04 22:37:06,522:INFO:IndexPage:Url hit...
2021-09-04 22:37:09,865:INFO:IndexPage:Did Profiling
2021-09-05 08:07:05,197:INFO:IndexPage:Url hit...
2021-09-05 08:30:58,159:INFO:IndexPage:Url hit...
2021-09-05 08:31:01,735:INFO:IndexPage:Did Profiling
2021-09-05 15:13:27,421:INFO:IndexPage:Url hit...
2021-09-05 15:13:30,667:INFO:IndexPage:Did Profiling
2021-09-06 07:46:51,523:INFO:IndexPage:Url hit...
2021-09-06 07:46:55,051:INFO:IndexPage:Did Profiling
